apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-volume
  labels:
    app: pihole
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/srv/pihole/etc"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - qingque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-volume
  labels:
    app: pihole
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/srv/pihole/dnsmasq.d"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - qingque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-volume-claim
spec:
  volumeName: pihole-etc-volume
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-volume-claim
spec:
  volumeName: pihole-dnsmasq-volume
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Boise"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: webpassword
                  name: pihole-secrets
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-etc-volume-mount
            - mountPath: /etc/dnsmasq.d
              name: pihole-dnsmasq-volume-mount
      volumes:
        - name: pihole-etc-volume-mount
          persistentVolumeClaim:
            claimName: pihole-etc-volume-claim
        - name: pihole-dnsmasq-volume-mount
          persistentVolumeClaim:
            claimName: pihole-dnsmasq-volume-claim
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - qingque
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-admin
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - name: pihole-admin
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  externalTrafficPolicy: Local