apiVersion: v1
kind: Secret
metadata:
  name: mimir-basicauth
type: Opaque
stringData:
  username:
  password:
---
apiVersion: v1
kind: Secret
metadata:
  name: unifi-auth
type: Opaque
stringData:
  password:
---
apiVersion: v1
kind: Secret
metadata:
  name: caddy-secrets
type: Opaque
stringData:
  domain:
  cloudflare-api-token:
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secrets
type: Opaque
stringData:
  cloudflared-token: