# After applying, run `kubectl rollout restart deployment argocd-server -n argocd`
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: "true"